-- Baseline: marketplace schema as produced by Hibernate ddl-auto=update on 2026-10-09.
-- Existing databases are baselined at version 1 and skip this file (spring.flyway.baseline-on-migrate).
-- Tables are listed alphabetically, so foreign keys are checked after all are created.

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `acceptance_criteria` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_id` binary(16) DEFAULT NULL,
  `description` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `job_id` binary(16) DEFAULT NULL,
  `item_order` int NOT NULL,
  `required` bit(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `contract_cancellations` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` decimal(19,2) DEFAULT NULL,
  `checkout_order_id` binary(16) DEFAULT NULL,
  `contract_id` binary(16) NOT NULL,
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `decided_at` datetime(6) DEFAULT NULL,
  `decided_by` binary(16) DEFAULT NULL,
  `funding_transaction_id` binary(16) DEFAULT NULL,
  `intent_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `job_id` binary(16) NOT NULL,
  `last_error` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `milestone_id` binary(16) NOT NULL,
  `next_attempt_at` datetime(6) DEFAULT NULL,
  `payment_refund_id` binary(16) DEFAULT NULL,
  `reason` varchar(2000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `reason_code` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `refund_key` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `refund_reference` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `refund_status` enum('FAILED','FAILED_RETRYABLE','PENDING','PROCESSING','SUCCEEDED','UNKNOWN') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `requested_by` binary(16) NOT NULL,
  `retryable` bit(1) NOT NULL,
  `simulation` bit(1) NOT NULL,
  `status` enum('CANCELLED','REFUND_PENDING','REJECTED','REQUESTED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cancellation_contract` (`contract_id`),
  UNIQUE KEY `uk_cancellation_milestone` (`milestone_id`),
  UNIQUE KEY `uk_cancellation_refund_key` (`refund_key`),
  KEY `idx_cancellation_due` (`retryable`,`next_attempt_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `contract_disputes` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` decimal(19,2) DEFAULT NULL,
  `checkout_order_id` binary(16) DEFAULT NULL,
  `claimed_at` datetime(6) DEFAULT NULL,
  `claimed_by` binary(16) DEFAULT NULL,
  `contract_id` binary(16) NOT NULL,
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `decision_at` datetime(6) DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `funding_transaction_id` binary(16) DEFAULT NULL,
  `job_id` binary(16) DEFAULT NULL,
  `last_error` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `milestone_id` binary(16) DEFAULT NULL,
  `next_attempt_at` datetime(6) DEFAULT NULL,
  `opened_at` datetime(6) DEFAULT NULL,
  `opened_by` binary(16) NOT NULL,
  `payment_refund_id` binary(16) DEFAULT NULL,
  `reason_code` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `refund_key` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `refund_reference` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `refund_status` enum('FAILED','FAILED_RETRYABLE','PENDING','PROCESSING','SUCCEEDED','UNKNOWN') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `resolution_hash` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `resolution_key` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `resolution_reason` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `resolved_at` datetime(6) DEFAULT NULL,
  `resolved_by` binary(16) DEFAULT NULL,
  `retryable` bit(1) NOT NULL,
  `status` enum('CANCELLED','DECISION_PENDING_REFUND','DECISION_PENDING_RELEASE','OPEN','RESOLVED_REFUND','RESOLVED_RELEASE','UNDER_REVIEW') COLLATE utf8mb4_unicode_ci NOT NULL,
  `submission_id` binary(16) DEFAULT NULL,
  `version` bigint NOT NULL,
  `moderation_due_at` datetime(6) DEFAULT NULL,
  `negotiation_outcome` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `negotiation_proposed_at` datetime(6) DEFAULT NULL,
  `negotiation_proposed_by` binary(16) DEFAULT NULL,
  `negotiation_reason` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `negotiation_until` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dispute_contract` (`contract_id`),
  UNIQUE KEY `uk_dispute_refund_key` (`refund_key`),
  KEY `idx_dispute_contract_status` (`contract_id`,`status`),
  KEY `idx_dispute_refund_due` (`status`,`next_attempt_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `contract_reviews` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comment` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `communication` int DEFAULT NULL,
  `completed_at` datetime(6) NOT NULL,
  `contract_id` binary(16) NOT NULL,
  `hidden_at` datetime(6) DEFAULT NULL,
  `invalidated_at` datetime(6) DEFAULT NULL,
  `job_id` binary(16) NOT NULL,
  `overall` int DEFAULT NULL,
  `published_at` datetime(6) DEFAULT NULL,
  `reported_at` datetime(6) DEFAULT NULL,
  `reported_by` binary(16) DEFAULT NULL,
  `requirements_or_quality` int DEFAULT NULL,
  `reviewee_id` binary(16) NOT NULL,
  `reviewer_id` binary(16) NOT NULL,
  `submitted_at` datetime(6) DEFAULT NULL,
  `timeliness` int DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_contract_reviewer` (`contract_id`,`reviewer_id`),
  KEY `idx_review_reviewee_public` (`reviewee_id`,`published_at`,`invalidated_at`),
  KEY `idx_review_due` (`completed_at`,`published_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `contract_settlements` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` decimal(19,2) NOT NULL,
  `checkout_order_id` binary(16) NOT NULL,
  `contract_id` binary(16) NOT NULL,
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `freelancer_id` binary(16) NOT NULL,
  `funding_transaction_id` binary(16) NOT NULL,
  `job_id` binary(16) NOT NULL,
  `last_error` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `milestone_id` binary(16) NOT NULL,
  `money_status` enum('FAILED','FAILED_RETRYABLE','PENDING','PROCESSING','SUCCEEDED','UNKNOWN') COLLATE utf8mb4_unicode_ci NOT NULL,
  `money_succeeded_at` datetime(6) DEFAULT NULL,
  `next_attempt_at` datetime(6) NOT NULL,
  `off_ramp_error` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `off_ramp_reference` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `off_ramp_status` enum('FAILED','FAILED_RETRYABLE','NOT_STARTED','PROCESSING','SUCCEEDED','UNKNOWN') COLLATE utf8mb4_unicode_ci NOT NULL,
  `on_chain_error` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `on_chain_reference` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `on_chain_status` enum('FAILED','FAILED_RETRYABLE','NOT_STARTED','PROCESSING','SUCCEEDED','UNKNOWN') COLLATE utf8mb4_unicode_ci NOT NULL,
  `payment_release_id` binary(16) DEFAULT NULL,
  `payment_release_reference` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payout_record_id` binary(16) DEFAULT NULL,
  `release_key` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `retryable` bit(1) NOT NULL,
  `simulation` bit(1) NOT NULL,
  `tax_error` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tax_reference` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tax_status` enum('FAILED','FAILED_RETRYABLE','NOT_STARTED','PROCESSING','SUCCEEDED','UNKNOWN') COLLATE utf8mb4_unicode_ci NOT NULL,
  `version` bigint NOT NULL,
  `freelancer_usd` decimal(19,2) DEFAULT NULL,
  `locked_usd_vnd_rate` decimal(19,6) DEFAULT NULL,
  `partner_payout_vnd` decimal(19,0) DEFAULT NULL,
  `platform_fee_usd` decimal(19,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_settlement_milestone` (`milestone_id`),
  UNIQUE KEY `uk_settlement_release_key` (`release_key`),
  UNIQUE KEY `uk_settlement_checkout` (`checkout_order_id`),
  KEY `idx_settlement_due` (`retryable`,`next_attempt_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `deliverable_requirements` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_id` binary(16) DEFAULT NULL,
  `description` varchar(2000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `job_id` binary(16) DEFAULT NULL,
  `item_order` int NOT NULL,
  `required` bit(1) NOT NULL,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `dispute_audit` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `action` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `actor_id` binary(16) NOT NULL,
  `after_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `before_status` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dispute_id` binary(16) NOT NULL,
  `idempotency_key` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reason` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `request_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_dispute_audit` (`dispute_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `dispute_evidence` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `actor_id` binary(16) NOT NULL,
  `dispute_id` binary(16) NOT NULL,
  `kind` enum('LINK','TEXT') COLLATE utf8mb4_unicode_ci NOT NULL,
  `sha256` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `evidence_text` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_dispute_evidence` (`dispute_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `dispute_evidence_batches` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `actor_id` binary(16) NOT NULL,
  `dispute_id` binary(16) NOT NULL,
  `idempotency_key` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dispute_evidence_batch_key` (`dispute_id`,`actor_id`,`idempotency_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `escrow_action_intents` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `action` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `actor_id` binary(16) NOT NULL,
  `build_session_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contract_id` binary(16) NOT NULL,
  `milestone_id` binary(16) NOT NULL,
  `original_transaction` text COLLATE utf8mb4_unicode_ci,
  `partial_transaction` text COLLATE utf8mb4_unicode_ci,
  `payload_hash` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payload_json` text COLLATE utf8mb4_unicode_ci,
  `signature` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKkr8b4jabv326auin4kf3k327w` (`build_session_id`),
  KEY `idx_escrow_action_contract` (`contract_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `escrow_contracts` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `arbiter_wallet` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `claim_signature` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `claim_submitted_at` datetime(6) DEFAULT NULL,
  `client_wallet` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contract_id` binary(16) NOT NULL,
  `escrow_address` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `freelancer_wallet` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fund_build_session` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fund_signature` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_chain_status` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `milestone_id` binary(16) NOT NULL,
  `mint` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `refund_signature` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `refund_submitted_at` datetime(6) DEFAULT NULL,
  `release_signature` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `release_submitted_at` datetime(6) DEFAULT NULL,
  `released_at` datetime(6) DEFAULT NULL,
  `resolution_signature` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `resolution_submitted_at` datetime(6) DEFAULT NULL,
  `settlement_retry_pending` bit(1) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKom6kjeyj0knr9cop5k0be44nu` (`contract_id`),
  UNIQUE KEY `UK7bw2d2992vy24vmd8008wt4fw` (`milestone_id`),
  KEY `idx_escrow_contract_milestone` (`milestone_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `freelancer_payout_records` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount_usd` decimal(20,6) NOT NULL,
  `amount_usd_net` decimal(20,6) NOT NULL,
  `amount_usdc_received` decimal(20,6) DEFAULT NULL,
  `amount_vnd_before_off_ramp_fee` decimal(20,0) DEFAULT NULL,
  `amount_vnd_estimated` decimal(20,0) DEFAULT NULL,
  `client_payment_confirmed_at` datetime(6) DEFAULT NULL,
  `client_payment_error` text COLLATE utf8mb4_unicode_ci,
  `client_payment_status` enum('CONFIRMED','FAILED','INVOICE_CREATED','INVOICE_SUBMITTED','NOT_STARTED','PAYMENT_SUBMITTED','RATE_CONFIRMED','RATE_SUBMITTED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `client_payment_submitted_at` datetime(6) DEFAULT NULL,
  `client_user_id` binary(16) NOT NULL,
  `freelancer_id` binary(16) NOT NULL,
  `freelancer_public_key` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `invoice_expires_at_epoch` bigint DEFAULT NULL,
  `invoice_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `invoice_pda` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `invoice_transaction_signature` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `job_id` binary(16) NOT NULL,
  `misa_certificate_id` binary(16) DEFAULT NULL,
  `misa_payout_transaction_id` binary(16) DEFAULT NULL,
  `off_ramp_completed_at` datetime(6) DEFAULT NULL,
  `off_ramp_completion_signature` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `off_ramp_completion_submitted_at` datetime(6) DEFAULT NULL,
  `off_ramp_error` text COLLATE utf8mb4_unicode_ci,
  `off_ramp_fee_vnd` decimal(20,0) DEFAULT NULL,
  `off_ramp_reference` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `off_ramp_status` enum('COMPLETED','COMPLETION_SUBMITTED','FAILED','NOT_STARTED','SIMULATED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `on_chain_off_ramp_error` text COLLATE utf8mb4_unicode_ci,
  `on_chain_off_ramp_status` enum('CONFIRMED','FAILED','NOT_STARTED','REQUEST_SUBMITTED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `on_ramp_client_public_key` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `on_ramp_client_usdc_ata` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `on_ramp_confirmed_at` datetime(6) DEFAULT NULL,
  `on_ramp_error` text COLLATE utf8mb4_unicode_ci,
  `on_ramp_fee_usd` decimal(20,6) NOT NULL,
  `on_ramp_network` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `on_ramp_purchase_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `on_ramp_receipt_pda` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `on_ramp_status` enum('CONFIRMED','FAILED','NOT_STARTED','SUBMITTED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `on_ramp_submitted_at` datetime(6) DEFAULT NULL,
  `on_ramp_transaction_signature` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `on_ramp_usd_amounte6` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payment_mint` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_transaction_signature` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payout_bank_account_holder_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payout_bank_account_number` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payout_bank_code` enum('ACB','AGRIBANK','BIDV','MBBANK','SACOMBANK','TECHCOMBANK','TPBANK','VIETCOMBANK','VIETINBANK','VPBANK') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rate_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rate_snapshot_pda` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rate_transaction_signature` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `simulated` bit(1) NOT NULL,
  `simulated_payout_at` datetime(6) DEFAULT NULL,
  `tax_rate_observed_at` datetime(6) DEFAULT NULL,
  `tax_rate_source` enum('FALLBACK_PLACEHOLDER','LIVE_COINGECKO','LIVE_OPEN_ER_API') COLLATE utf8mb4_unicode_ci NOT NULL,
  `tax_usd_to_vnd_rate` decimal(20,2) NOT NULL,
  `taxable_amount_vnd` decimal(20,0) NOT NULL,
  `treasury_public_key` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `treasury_usdc_ata` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `usdc_to_vnd_rate` decimal(20,2) DEFAULT NULL,
  `usdc_to_vnd_rate_observed_at` datetime(6) DEFAULT NULL,
  `usdc_to_vnd_rate_source` enum('FALLBACK_PLACEHOLDER','LIVE_COINGECKO','LIVE_OPEN_ER_API') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `withdrawal_confirmed_at` datetime(6) DEFAULT NULL,
  `withdrawal_fiat_amount_vnd` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `withdrawal_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `withdrawal_pda` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `withdrawal_submitted_at` datetime(6) DEFAULT NULL,
  `withdrawal_token_amount` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `withdrawal_transaction_signature` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_settlement_id` binary(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKbx5aktt82ffynrttdmeglsig3` (`job_id`),
  UNIQUE KEY `UKk081q7jiccy8tveqsgf3fn40t` (`contract_settlement_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `funding_transactions` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` decimal(19,2) NOT NULL,
  `checkout_order_id` binary(16) DEFAULT NULL,
  `client_user_id` binary(16) NOT NULL,
  `contract_id` binary(16) NOT NULL,
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `idempotency_key` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `milestone_id` binary(16) NOT NULL,
  `payer_bank_account_holder_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payer_bank_account_number` varchar(34) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payer_bank_code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payment_method_id` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('FAILED','PENDING','PROCESSING','SUCCEEDED','UNKNOWN') COLLATE utf8mb4_unicode_ci NOT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_funding_client_key` (`client_user_id`,`idempotency_key`),
  KEY `idx_funding_status_updated` (`status`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `job_applications` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `freelancer_id` binary(16) NOT NULL,
  `job_id` binary(16) NOT NULL,
  `status` enum('ACCEPTED','CANCELLED','PENDING','REJECTED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `accepted_terms_fingerprint` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `terms_accepted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKik4qv1re4y2b67adfcx4siu8s` (`job_id`,`freelancer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `job_skills` (
  `job_id` binary(16) NOT NULL,
  `skill` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `skill_order` int NOT NULL,
  PRIMARY KEY (`job_id`,`skill_order`),
  CONSTRAINT `FK1gb74tysr9vkypwivvvovxq1f` FOREIGN KEY (`job_id`) REFERENCES `jobs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `job_submissions` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deliverable_url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `freelancer_id` binary(16) NOT NULL,
  `job_id` binary(16) NOT NULL,
  `reviewed_at` datetime(6) DEFAULT NULL,
  `reviewer_feedback` text COLLATE utf8mb4_unicode_ci,
  `status` enum('APPROVED','DISPUTED','REVISION_REQUESTED','SUBMITTED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `summary` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `submission_version` int NOT NULL,
  `contract_id` binary(16) DEFAULT NULL,
  `idempotency_key` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `milestone_id` binary(16) DEFAULT NULL,
  `payload_hash` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `review_criterion_ids_json` text COLLATE utf8mb4_unicode_ci,
  `review_deliverable_ids_json` text COLLATE utf8mb4_unicode_ci,
  `review_due_at` datetime(6) DEFAULT NULL,
  `review_grace_due_at` datetime(6) DEFAULT NULL,
  `reviewed_automatically` bit(1) NOT NULL,
  `submitted_at` datetime(6) DEFAULT NULL,
  `submitted_late` bit(1) NOT NULL,
  `review_reminder_count` int NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKljucp4p1kaa7fv8ikb1fjmpsk` (`job_id`,`submission_version`),
  UNIQUE KEY `uk_submission_actor_key` (`freelancer_id`,`idempotency_key`),
  KEY `idx_submission_review_due` (`status`,`review_due_at`,`review_grace_due_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `jobs` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `budget_usd` decimal(19,2) NOT NULL,
  `checkout_order_id` binary(16) DEFAULT NULL,
  `client_user_id` binary(16) NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `freelancer_id` binary(16) DEFAULT NULL,
  `misa_certificate_id` binary(16) DEFAULT NULL,
  `misa_payout_transaction_id` binary(16) DEFAULT NULL,
  `payer_bank_account_holder_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payer_bank_account_number` varchar(34) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payer_bank_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('AWAITING_PAYMENT','CANCELLED','COMPLETED','IN_PROGRESS','OPEN','REVISION_REQUESTED','SUBMITTED_FOR_REVIEW') COLLATE utf8mb4_unicode_ci NOT NULL,
  `tax_export_status` enum('FAILED','NOT_ATTEMPTED','SUCCESS') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'OTHER',
  `delivery_due_at` datetime(6) DEFAULT NULL,
  `max_revisions` int NOT NULL,
  `review_window_hours` int NOT NULL,
  `payment_flow_version` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `member_profiles` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `availability` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `avatar_url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bio` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `company_name` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `company_website` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country_code` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `edited_at` datetime(6) DEFAULT NULL,
  `email_verification` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `headline` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hourly_rate_usd` decimal(12,2) DEFAULT NULL,
  `identity_verification` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `languages_json` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payment_verification` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `skills_json` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` binary(16) NOT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_member_profile_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `milestones` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` decimal(19,2) NOT NULL,
  `contract_id` binary(16) NOT NULL,
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('CANCELLED','DISPUTED','FUNDED','IN_PROGRESS','PENDING_FUNDING','REFUNDED','REFUND_PENDING','RELEASED','RELEASE_PENDING','SUBMITTED') COLLATE utf8mb4_unicode_ci NOT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKkv5qtuoltxci85pbvgavm2awc` (`contract_id`),
  KEY `idx_milestone_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `notifications` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` decimal(20,0) DEFAULT NULL,
  `is_read` bit(1) NOT NULL,
  `job_id` binary(16) DEFAULT NULL,
  `message` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `recipient_user_id` binary(16) NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` enum('CANCELLATION_REJECTED','CANCELLATION_REQUESTED','DISPUTE_DECIDED','DISPUTE_OPENED','FUNDING_CONFIRMED','FUNDING_REMINDER','JOB_ASSIGNED','JOB_CANCELLED','PAYMENT_RECEIVED','PAYMENT_SENT','PAYOUT_FAILED','REFUND_CONFIRMED','REFUND_PENDING','RELEASE_CONFIRMED','REVIEW_AUTO_APPROVED','REVIEW_GRACE_STARTED','REVIEW_INVITED','REVIEW_PUBLISHED','REVIEW_REMINDER','REVISION_REQUESTED','TAX_EXPORT_FAILED','WORK_APPROVED','WORK_SUBMITTED') COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `payment_flow_evidence` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` decimal(19,6) DEFAULT NULL,
  `contract_id` binary(16) NOT NULL,
  `currency` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `evidence_source` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `idempotency_key` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `job_id` binary(16) NOT NULL,
  `kind` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `milestone_id` binary(16) NOT NULL,
  `payment_flow_id` binary(16) NOT NULL,
  `reference` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_payment_flow_evidence_flow` (`payment_flow_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `payment_flow_steps` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `account_address` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` decimal(19,6) DEFAULT NULL,
  `beneficiary` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `build_session_id` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confirmed_at` datetime(6) DEFAULT NULL,
  `currency` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `evidence_source` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fee_usdc` decimal(19,6) DEFAULT NULL,
  `idempotency_key` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kind` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payment_flow_id` binary(16) NOT NULL,
  `payout_vnd` decimal(19,0) DEFAULT NULL,
  `provider` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quote_expires_at` datetime(6) DEFAULT NULL,
  `rate_id` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reference` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `retry_after` datetime(6) DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `submitted_at` datetime(6) DEFAULT NULL,
  `token_account` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `transaction_signature` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `version` bigint NOT NULL,
  `vnd_rate` decimal(19,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_flow_step` (`payment_flow_id`,`kind`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `payment_flows` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `client_id` binary(16) NOT NULL,
  `contract_id` binary(16) NOT NULL,
  `delivery_due_at` datetime(6) DEFAULT NULL,
  `escrow_usdc` decimal(19,6) NOT NULL,
  `freelancer_id` binary(16) NOT NULL,
  `funding_expires_at` datetime(6) DEFAULT NULL,
  `gross_usd` decimal(19,2) NOT NULL,
  `job_id` binary(16) NOT NULL,
  `max_revisions` int NOT NULL,
  `milestone_id` binary(16) NOT NULL,
  `mint` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `network` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payer_bank_account_holder_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payer_bank_account_number` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payer_bank_code` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `platform_fee_usd` decimal(19,2) NOT NULL,
  `quote_expires_at` datetime(6) DEFAULT NULL,
  `quote_source` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `review_window_hours` int NOT NULL,
  `terms_version` int NOT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_flow_milestone` (`milestone_id`),
  UNIQUE KEY `uk_payment_flow_contract` (`contract_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `portfolio_items` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `completed_at` date DEFAULT NULL,
  `description` varchar(2000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `project_url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `skills_json` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `sort_order` int NOT NULL,
  `thumbnail_url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` varchar(160) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` binary(16) NOT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_portfolio_owner_sort` (`user_id`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `review_audits` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `action` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `actor_id` binary(16) NOT NULL,
  `after_state` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `before_state` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `reason` varchar(2000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `request_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `review_id` binary(16) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_review_audit_review` (`review_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `roles` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKofx66keruapi6vyqpv6f2or37` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `submission_evidence` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kind` enum('ACCEPTANCE_CRITERION','DELIVERABLE') COLLATE utf8mb4_unicode_ci NOT NULL,
  `requirement_id` binary(16) NOT NULL,
  `submission_id` binary(16) NOT NULL,
  `url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_evidence_submission` (`submission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `tax_certificate_records` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount_usd` decimal(20,6) NOT NULL,
  `certificate_number` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `certificate_symbol` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `client_user_id` binary(16) NOT NULL,
  `freelancer_id` binary(16) NOT NULL,
  `issued_at` datetime(6) DEFAULT NULL,
  `job_id` binary(16) NOT NULL,
  `last_error` text COLLATE utf8mb4_unicode_ci,
  `last_synced_at` datetime(6) DEFAULT NULL,
  `lookup_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `misa_certificate_id` binary(16) DEFAULT NULL,
  `misa_payout_transaction_id` binary(16) DEFAULT NULL,
  `misa_status_raw` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `misa_taxpayer_id` binary(16) DEFAULT NULL,
  `payout_record_id` binary(16) DEFAULT NULL,
  `rate_observed_at` datetime(6) DEFAULT NULL,
  `rate_source` enum('FALLBACK_PLACEHOLDER','LIVE_COINGECKO','LIVE_OPEN_ER_API') COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('ACCEPTED','CANCELLED','CORRECTION_REQUIRED','DRAFT','EXPORT_FAILED','PENDING_EXPORT','REJECTED','REPLACED','SIGNED','SUBMITTED','SUBMITTING') COLLATE utf8mb4_unicode_ci NOT NULL,
  `submission_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `submitted_at` datetime(6) DEFAULT NULL,
  `tax_authority_reference` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tax_withheld_vnd` decimal(20,0) DEFAULT NULL,
  `taxable_income_vnd` decimal(20,0) NOT NULL,
  `transaction_reference` varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `usd_to_vnd_rate` decimal(20,2) NOT NULL,
  `certificate_create_key` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK45175weqd6fg01hph0dx3bbxh` (`job_id`),
  UNIQUE KEY `UK9knayu0xr92exnb0qn0m4kqbo` (`misa_certificate_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `user_roles` (
  `user_id` binary(16) NOT NULL,
  `role_id` binary(16) NOT NULL,
  PRIMARY KEY (`user_id`,`role_id`),
  KEY `FKh8ciramu9cc9q3qcqiv4ue8a6` (`role_id`),
  CONSTRAINT `FKh8ciramu9cc9q3qcqiv4ue8a6` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`),
  CONSTRAINT `FKhfh9dx7w3ubf1co1vdev94g3f` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `users` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `auth_provider` enum('LOCAL') COLLATE utf8mb4_unicode_ci NOT NULL,
  `bank_account_holder_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bank_account_number` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bank_code` enum('ACB','AGRIBANK','BIDV','MBBANK','SACOMBANK','TECHCOMBANK','TPBANK','VIETCOMBANK','VIETINBANK','VPBANK') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `display_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `enabled` bit(1) NOT NULL,
  `identity_number` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nationality` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `refresh_token` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tax_address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tax_code` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_type` enum('CLIENT','FREELANCER') COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK6dotkott2kjsp8vw4d0m25fb7` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `wallet_link_challenges` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expires_at` datetime(6) NOT NULL,
  `message` varchar(400) COLLATE utf8mb4_unicode_ci NOT NULL,
  `used_at` datetime(6) DEFAULT NULL,
  `user_id` binary(16) NOT NULL,
  `wallet_address` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `wallets` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `public_key` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` binary(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK2huajslu7vxs5fy4at41gn4w7` (`public_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `work_contracts` (
  `id` binary(16) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `updated_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `budget_usd` decimal(19,2) NOT NULL,
  `client_user_id` binary(16) NOT NULL,
  `delivery_due_at` datetime(6) DEFAULT NULL,
  `description_snapshot` text COLLATE utf8mb4_unicode_ci,
  `freelancer_id` binary(16) NOT NULL,
  `funding_reminder_sent_at` datetime(6) DEFAULT NULL,
  `job_id` binary(16) NOT NULL,
  `max_revisions` int NOT NULL,
  `payment_rail` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `review_window_hours` int NOT NULL,
  `revisions_used` int NOT NULL,
  `status` enum('ACTIVE','CANCELLED','COMPLETED','DISPUTED','PENDING_FUNDING','REVISION','UNDER_REVIEW') COLLATE utf8mb4_unicode_ci NOT NULL,
  `title_snapshot` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `version` bigint NOT NULL,
  `accepted_terms_fingerprint` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `client_terms_accepted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKhxmb33it616uidgh4klyt74w1` (`job_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
