spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    com.payment.backend: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET}

internal:
  api:
    key: ${INTERNAL_API_KEY}

bofa:
  checkout:
    base-url: ${BOFA_BASE_URL:https://api-m.sandbox.paypal.com}
